#!/usr/bin/env python3
"""build_web.py - Inline web assets into a single self-contained HTML file.

The C server embeds exactly one document, so the ES modules used during
development are inlined here. The four modules share one scope (top-level
names are unique across files and this script verifies that), so bundling is
a deterministic concatenation with import/export syntax stripped.

Usage: python3 scripts/build_web.py <web-dir> <output.html>
Fails loudly (exit 1) on missing, empty or ambiguous assets. No fallback.
"""
import re
import sys
from pathlib import Path

MODULE_ORDER = ["i18n.js", "compare.js", "api.js", "lab.js"]

IMPORT_RE = re.compile(r'^\s*import\s*\{[^}]*\}\s*from\s*"\./[^"]+";\s*$', re.MULTILINE)
DECL_RE = re.compile(r"^(?:export\s+)?(?:const|let|function|class)\s+([A-Za-z0-9_$]+)", re.MULTILINE)


def read_asset(root: Path, name: str) -> str:
    path = root / name
    if not path.is_file():
        raise SystemExit("build_web: missing asset: %s" % path)
    text = path.read_text(encoding="utf-8")
    if not text.strip():
        raise SystemExit("build_web: empty asset: %s" % path)
    return text


def strip_module_syntax(source: str) -> str:
    source = IMPORT_RE.sub("", source)
    return re.sub(r"^export\s+(?=(?:async\s+)?(?:const|let|function|class)\s)", "", source, flags=re.MULTILINE)


def declared_names(source: str) -> list:
    """Top-level declarations, ignoring matches inside strings/comments."""
    code_mask = mask_code(source)
    names = []
    for match in DECL_RE.finditer(source):
        if code_mask[match.start()]:
            names.append(match.group(1))
    return names


def mask_code(source: str) -> list:
    """True for each index that is real code (not string/comment content)."""
    mask = [True] * len(source)
    index = 0
    length = len(source)
    state = "code"
    while index < length:
        char = source[index]
        nxt = source[index + 1] if index + 1 < length else ""
        if state == "code":
            if char == "/" and nxt == "/":
                state = "line"
                mask[index] = mask[index + 1] = False
                index += 2
                continue
            if char == "/" and nxt == "*":
                state = "block"
                mask[index] = mask[index + 1] = False
                index += 2
                continue
            if char in ('"', "'", "`"):
                state = char
                mask[index] = False
        elif state == "line":
            mask[index] = False
            if char == "\n":
                state = "code"
        elif state == "block":
            mask[index] = False
            if char == "*" and nxt == "/":
                mask[index + 1] = False
                index += 2
                state = "code"
                continue
        else:
            mask[index] = False
            if char == "\\":
                mask[index] = False
                if index + 1 < length:
                    mask[index + 1] = False
                index += 2
                continue
            if char == state:
                state = "code"
        index += 1
    return mask


def check_unique_names(modules: dict) -> None:
    seen: dict = {}
    clashes = []
    for name, source in modules.items():
        for symbol in declared_names(source):
            if symbol in seen:
                clashes.append("%s (%s and %s)" % (symbol, seen[symbol], name))
            else:
                seen[symbol] = name
    if clashes:
        raise SystemExit("build_web: top-level name collision: " + ", ".join(sorted(set(clashes))))


def bundle_script(root: Path) -> str:
    modules = {name: read_asset(root, name) for name in MODULE_ORDER}
    check_unique_names(modules)
    parts = ["/* Bundle generated by scripts/build_web.py. Edit web/*.js, not this. */"]
    parts.append("(function () {\n'use strict';")
    for name in MODULE_ORDER:
        parts.append("/* ---- web/%s ---- */" % name)
        parts.append(strip_module_syntax(modules[name]))
    parts.append("})();")
    return "\n".join(parts)


def bundle_html(root: Path) -> str:
    template = read_asset(root, "index.html")
    css = read_asset(root, "styles.css")
    script = bundle_script(root)

    inlined = re.sub(
        r'<link rel="stylesheet" href="styles\.css">',
        lambda _: "<style>\n%s\n</style>" % css,
        template,
    )
    inlined = re.sub(
        r'<script type="module" src="lab\.js"></script>',
        lambda _: "<script>\n%s\n</script>" % script,
        inlined,
    )
    if 'href="styles.css"' in inlined or 'src="lab.js"' in inlined:
        raise SystemExit("build_web: asset references were not replaced")
    return inlined


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: build_web.py <web-dir> <output.html>", file=sys.stderr)
        return 2
    root = Path(sys.argv[1])
    output = Path(sys.argv[2])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(bundle_html(root), encoding="utf-8")
    print("build_web: %d bytes -> %s" % (output.stat().st_size, output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
