#!/usr/bin/env python3
"""embed.py - Generate a C header with a file embedded as a byte array.

Usage: python3 scripts/embed.py <input> <output> <symbol>
Fails loudly on missing input (no silent fallback); output is deterministic.
"""
import sys


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: embed.py <input> <output> <symbol>", file=sys.stderr)
        return 2
    src, dst, symbol = sys.argv[1], sys.argv[2], sys.argv[3]
    try:
        with open(src, "rb") as handle:
            data = handle.read()
    except OSError as exc:
        print("embed: cannot read %s: %s" % (src, exc), file=sys.stderr)
        return 1
    with open(dst, "w", encoding="utf-8") as handle:
        guard = "_EMBED_%s_H" % "".join(c if c.isalnum() else "_" for c in symbol.upper())
        handle.write("#ifndef %s\n#define %s\n\n" % (guard, guard))
        handle.write("/* Generated by scripts/embed.py from %s. Do not edit. */\n" % src)
        handle.write("static const unsigned char %s[] = {" % symbol)
        for index, byte in enumerate(data):
            if index % 12 == 0:
                handle.write("\n   ")
            handle.write(" %d," % byte)
        handle.write("\n};\n")
        handle.write("static const unsigned long %s_len = %dUL;\n\n" % (symbol, len(data)))
        handle.write("#endif\n")
    print("embed: %d bytes %s -> %s [%s]" % (len(data), src, dst, symbol))
    return 0


if __name__ == "__main__":
    sys.exit(main())
